server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourun?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: openpass
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        time_zone: Asia/Seoul
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  application:
    name: yourun
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.umc.yourun
#  security:
#    oauth2:
#      client:
#        registration:
#          custom-client:
##            client-id: your-client-id
##            client-secret: your-client-secret
#            authorization-grant-type: password
#            scope: read write
#            token-uri: http://${SERVER_HOST}:8080/oauth/token
#            client-authentication-method: post