server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10         # 최대 커넥션 개수
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  application:
    name: yourun
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://${SERVER_HOST}:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.umc.yourun
  security:
    oauth2:
      client:
        registration:
          custom-client:
            authorization-grant-type: password
            scope: read write
            token-uri: http://${SERVER_HOST}:8080/oauth/token
            client-authentication-method: post
logging:
  level:
    root: INFO
    com.umc.yourun: DEBUG  # 우리 프로젝트 로그만 DEBUG로
    org.springframework.context.support: OFF
    org.springframework.boot.web: OFF
    reactor.core: OFF
    io.netty: OFF
    org.apache.catalina: OFF
    com.zaxxer.hikari: OFF  # HikariCP 관련 로그
    org.hibernate: OFF
