server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/yourun
    username: dev_user
    password: dev_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Seoul
  application:
    name: yourun
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.umc.yourun
  security:
    oauth2:
      client:
        registration:
          custom-client:
#            client-id: your-client-id
#            client-secret: your-client-secret
            authorization-grant-type: password
            scope: read write
            token-uri: http://localhost:8080/oauth/token
            client-authentication-method: post
