name: Yourun Dev CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Create application.yml  # application.yml 파일 생성 최적화
        run: |
          mkdir -p ./src/main/resources
          cat << EOF > ./src/main/resources/application.yml
          ${{ secrets.APPLICATION_YML }}
          EOF
        shell: bash

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon --parallel --build-cache

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yourunServer
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: yourunServer
          path: build/libs/

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # 최신 JAR 파일 찾기
          JAR_FILE=$(ls -t build/libs/*.jar | grep -v plain | head -n 1)
          
          # JAR 파일 전송
          rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" \
            "$JAR_FILE" ${EC2_USERNAME}@${EC2_HOST}:/home/${EC2_USERNAME}/yourunServer.jar
          
          # 실행 스크립트 생성 및 전송
          cat << 'EOF' > start_server.sh
          #!/bin/bash
          kill -9 $(pgrep -f 'java -jar') || true
          sleep 5
          cd /home/${EC2_USERNAME}
          nohup java -jar yourunServer.jar > app.log 2>&1 </dev/null &
          sleep 10
          if pgrep -f 'java -jar' > /dev/null; then
            echo "Server started successfully"
            exit 0
          else
            echo "Server failed to start"
            exit 1
          fi
          EOF
          
          # 실행 권한 부여 및 전송
          chmod +x start_server.sh
          scp -i private_key.pem -o StrictHostKeyChecking=no \
            start_server.sh ${EC2_USERNAME}@${EC2_HOST}:/home/${EC2_USERNAME}/
          
          # 스크립트 실행
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_HOST} \
            "bash /home/${EC2_USERNAME}/start_server.sh"
          
          rm -f private_key.pem